CREATE OR ALTER PROCEDURE COMMON.SP_LOAD_LOOKUP_DETAIL_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO COMMON.STAGING_LOOKUP_DETAIL
    FROM @COMMON.ONEVIEW_STAGE/lookupDetails
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;

    UPDATE COMMON.STAGING_LOOKUP_DETAIL as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE COMMON.STAGING_LOOKUP_DETAIL as Target
    SET
        Target.GroupID = src._ID
    FROM COMMON.Lookup_Group src
    WHERE src.OneViewID = Target.GroupID
    AND src.ClientID = Target.ClientId;

    RETURN 1;

END';