CREATE OR ALTER PROCEDURE COMMON.SP_LOAD_CLIENT_USER_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO COMMON.STAGING_CLIENT_USERS
    FROM @COMMON.ONEVIEW_STAGE/clientUsers
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;

    UPDATE COMMON.STAGING_CLIENT_USERS as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE COMMON.STAGING_CLIENT_USERS as Target
    SET 
        Target.UserID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMUSER src
    WHERE target.EMAIL = src.EMAIL;

    RETURN 1;

END';
