CREATE OR ALTER PROCEDURE COMMON.SP_MASTER_INGESTION_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
	BEGIN
		-- Load data into staging tables
		---COMMON
		CALL COMMON.SP_LOAD_COUNTRY_STAGING();
		CALL COMMON.SP_LOAD_LANGUAGE_STAGING();
		CALL COMMON.SP_LOAD_REGION_STAGING();
		CALL COMMON.SP_LOAD_LOOKUP_GROUP_STAGING();
		CALL COMMON.SP_LOAD_LOOKUP_DETAIL_STAGING();
		CALL COMMON.SP_LOAD_CLIENT_VENDOR_STAGING();

END';