CREATE OR ALTER PROCEDURE ONEVIEW.SP_LOAD_VENDOR()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

MERGE INTO ONEVIEW.DIMVENDOR AS T
USING (
	SELECT
		VENDORID,
		REFERENCE,
		VENDORGUID,
		VENDOR,
		DESCRIPTION
	FROM ONEVIEW.STAGINGVENDORS
) AS S
ON T.VENDORID = S.VENDORID
AND T.REFERENCE = S.REFERENCE
AND T.VENDORGUID = S.VENDORGUID
AND T.VENDOR = S.VENDOR
WHEN MATCHED
THEN UPDATE SET
	T.REFERENCE = S.REFERENCE,
	T.VENDORGUID = S.VENDORGUID,
	T.VENDOR = S.VENDOR,
	T.DESCRIPTION = S.DESCRIPTION
WHEN NOT MATCHED THEN
INSERT (
	VENDORID,
	REFERENCE,
	VENDORGUID,
	VENDOR,
	DESCRIPTION,
    _INSERTEDDATE
) VALUES (
	S.VENDORID,
	S.REFERENCE,
	S.VENDORGUID,
	S.VENDOR,
	S.DESCRIPTION,
    CURRENT_TIMESTAMP()
);

DELETE FROM ONEVIEW.STAGINGVENDORS;

RETURN 1;


END';

CALL ONEVIEW.SP_LOAD_VENDOR();

SELECT *
FROM ONEVIEW.DIMVENDOR;

