CREATE OR ALTER PROCEDURE ONEVIEW.SP_LOAD_VENDOR_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ONEVIEW.STAGINGVENDORS
    FROM @ONEVIEW.ONEVIEW_STAGE/admin/vendors
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;


    RETURN 1;

END';

CALL ONEVIEW.SP_LOAD_VENDOR_STAGING();

SELECT *
FROM ONEVIEW.STAGINGVENDORS
