create or replace TABLE ONEVIEW.DIMVENDOR (
	_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	VENDORID NUMBER(38,0) NOT NULL,
	REFERENCE VARCHAR(4) NOT NULL,
	VENDORGUID VARCHAR(32) NOT NULL,
	VENDOR VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	_INSERTEDDATE TIMESTAMP_NTZ(9) NOT NULL,
	_UPDATEDDATE TIMESTAMP_NTZ(9),
	primary key (_ID)
);