CREATE OR REPLACE PROCEDURE ORGANISATION.SP_LOAD_COMPANY_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ORGANISATION.STAGING_COMPANY
    FROM @COMMON.ONEVIEW_STAGE/companies
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;

    UPDATE ORGANISATION.STAGING_COMPANY as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE ORGANISATION.STAGING_COMPANY as Target
    SET
        Target.LanguageID = src._ID
    FROM COMMON.LANGUAGE src
    WHERE src.OneViewId = Target.LanguageId;

    RETURN 1;

END';