CREATE OR ALTER PROCEDURE ORGANISATION.SP_LOAD_USER_COST_CENTRE_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
	COPY INTO ORGANISATION.STAGING_USER_COST_CENTRE
	FROM @COMMON.ONEVIEW_STAGE/userCostCentre
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	FILE_FORMAT = (TYPE = ''PARQUET'')
	ON_ERROR=CONTINUE
	PURGE = TRUE;

	UPDATE ORGANISATION.STAGING_USER_COST_CENTRE as Target
	SET 
		Target.ClientID = src._ID
	FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
	WHERE Target.CLIENTREFERENCE = src.CLIENTREFERENCE;

	UPDATE ORGANISATION.STAGING_USER_COST_CENTRE as Target
	SET
		Target.UserID = src._ID
	FROM NEBCOREODMSFDEV.COMMON.DIMUSER src
	WHERE src.OneViewID = Target.UserID
	AND src.ClientID = Target.ClientId;

	UPDATE ORGANISATION.STAGING_USER_COST_CENTRE as Target
	SET
		Target.CostCentreID = src._ID
	FROM ORGANISATION.COST_CENTRE src
	WHERE src.OneViewID = Target.CostCentreID
	AND src.ClientID = Target.ClientId;

	RETURN 1;

END';