CREATE OR ALTER PROCEDURE ORGANISATION.SP_LOAD_COST_CENTRE_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ORGANISATION.STAGING_COST_CENTRE
    FROM @COMMON.ONEVIEW_STAGE/costCentres
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;

    UPDATE ORGANISATION.STAGING_COST_CENTRE as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE ORGANISATION.STAGING_COST_CENTRE as Target
    SET
        Target.CompanyID = src._ID
    FROM Organisation.Company src
    WHERE src.OneViewID = Target.CompanyID
    AND src.ClientID = Target.ClientId;

    RETURN 1;

END';