CREATE OR ALTER PROCEDURE ORGANISATION.SP_MASTER_INGESTION()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN

		CALL ORGANISATION.SP_LOAD_ALLOCATION_GROUP();
		CALL ORGANISATION.SP_LOAD_ALLOCATION_GROUP_STAGING();

		CALL ORGANISATION.SP_LOAD_BRAND_STAGING();
		CALL ORGANISATION.SP_LOAD_BRAND();
		
		CALL ORGANISATION.SP_LOAD_BUSINESS_UNIT_STAGING();
		CALL ORGANISATION.SP_LOAD_BUSINESS_UNIT();
		
		CALL ORGANISATION.SP_LOAD_CAPACITY_GROUP_STAGING();
		CALL ORGANISATION.SP_LOAD_CAPACITY_GROUP();
		
		CALL ORGANISATION.SP_LOAD_COMPANY_STAGING();
		CALL ORGANISATION.SP_LOAD_COMPANY();
		
		CALL ORGANISATION.SP_LOAD_DIVISION_STAGING();
		CALL ORGANISATION.SP_LOAD_DIVISION();
		
		CALL ORGANISATION.SP_LOAD_COST_CENTRE_STAGING();
		CALL ORGANISATION.SP_LOAD_COST_CENTRE();
		
		CALL ORGANISATION.SP_LOAD_EMPLOYEE_STAGING();
		CALL ORGANISATION.SP_LOAD_EMPLOYEE();
		
		CALL ORGANISATION.SP_LOAD_OWNER_TYPE_STAGING();
		CALL ORGANISATION.SP_LOAD_OWNER_TYPE();
		
		CALL ORGANISATION.SP_LOAD_OWNER_STAGING();
		CALL ORGANISATION.SP_LOAD_OWNER();
		
		CALL ORGANISATION.SP_LOAD_ACCOUNT_STAGING();
		CALL ORGANISATION.SP_LOAD_ACCOUNT();
		
		CALL ORGANISATION.SP_LOAD_ENTITY_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY();
		
		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER();
		
		CALL ORGANISATION.SP_LOAD_ENTITY_PRODUCT_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_PRODUCT();
		
		CALL ORGANISATION.SP_LOAD_ENTITY_ENRICHMENT_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_ENRICHMENT();

		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER();

		RETURN 1;

END';