CREATE OR ALTER PROCEDURE ORGANISATION.SP_MASTER_INGESTION_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN
		CALL ORGANISATION.SP_LOAD_ALLOCATION_GROUP_STAGING();
		CALL ORGANISATION.SP_LOAD_BRAND_STAGING();
		CALL ORGANISATION.SP_LOAD_BUSINESS_UNIT_STAGING();
		CALL ORGANISATION.SP_LOAD_CAPACITY_GROUP_STAGING();
		CALL ORGANISATION.SP_LOAD_COMPANY_STAGING();
		CALL ORGANISATION.SP_LOAD_DIVISION_STAGING();
		CALL ORGANISATION.SP_LOAD_COST_CENTRE_STAGING();
		CALL ORGANISATION.SP_LOAD_EMPLOYEE_STAGING();
		CALL ORGANISATION.SP_LOAD_OWNER_TYPE_STAGING();
		CALL ORGANISATION.SP_LOAD_OWNER_STAGING();
		CALL ORGANISATION.SP_LOAD_ACCOUNT_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_PRODUCT_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_ENRICHMENT_STAGING();
		CALL ORGANISATION.SP_LOAD_ENTITY_OWNER_STAGING();

END';