CREATE OR ALTER PROCEDURE  COMMON.SP_LOAD_COUNTRY_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 
'BEGIN
    COPY INTO Common.STAGING_COUNTRY
    FROM @ONEVIEW_STAGE/admin/countries/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    RETURN 1;

END';