CREATE OR ALTER PROCEDURE  COMMON.SP_LOAD_LOOKUP_GROUP_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO COMMON.STAGING_LOOKUP_GROUP
    FROM @COMMON.ONEVIEW_STAGE/lookupGroups/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    
    FORCE = TRUE;

    UPDATE COMMON.STAGING_LOOKUP_GROUP as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    

    RETURN 1;

END';