CREATE OR ALTER PROCEDURE COMMON.SP_LOAD_CLIENT_VENDOR_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO COMMON.STAGING_CLIENT_VENDOR
    FROM @COMMON.ONEVIEW_STAGE/clientVendors/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    UPDATE COMMON.STAGING_CLIENT_VENDOR as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE COMMON.STAGING_CLIENT_VENDOR as Target
    SET 
        Target.VendorID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMVENDOR src
    WHERE target.VendorReference = src.REFERENCE;

    UPDATE COMMON.STAGING_CLIENT_VENDOR as Target
    SET
        Target.TypeDetailID = src._ID
    FROM COMMON.Lookup_Detail src
    WHERE src.OneViewID = Target.TypeDetailID
    AND src.ClientID = Target.ClientId;

    UPDATE COMMON.STAGING_CLIENT_VENDOR as Target
    SET
        Target.StatusDetailID = src._ID
    FROM COMMON.Lookup_Detail src
    WHERE src.OneViewID = Target.StatusDetailID
    AND src.ClientID = Target.ClientId;

    RETURN 1;

END';
