CREATE OR ALTER PROCEDURE COMMON.SP_LOAD_REGION_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 
'BEGIN
    COPY INTO Common.STAGING_REGION
    FROM @ONEVIEW_STAGE/regions/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    UPDATE Common.STAGING_REGION as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    RETURN 1;

END';

