CREATE OR ALTER PROCEDURE COMMON.SP_MASTER_INGESTION()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN
	CALL COMMON.SP_LOAD_COUNTRY_STAGING();
	CALL COMMON.SP_LOAD_COUNTRY();

	CALL COMMON.SP_LOAD_LANGUAGE_STAGING();
	CALL COMMON.SP_LOAD_LANGUAGE();

	CALL COMMON.SP_LOAD_REGION_STAGING();
	CALL COMMON.SP_LOAD_REGION();

	CALL COMMON.SP_LOAD_LOOKUP_GROUP_STAGING();
	CALL COMMON.SP_LOAD_LOOKUP_GROUP();

	CALL COMMON.SP_LOAD_LOOKUP_DETAIL_STAGING();
	CALL COMMON.SP_LOAD_LOOKUP_DETAIL();

	CALL COMMON.SP_LOAD_CLIENT_VENDOR_STAGING();
	CALL COMMON.SP_LOAD_CLIENT_VENDOR();

	CALL COMMON.SP_LOAD_CLIENT_USER_STAGING();
	CALL COMMON.SP_LOAD_CLIENT_USER();

	RETURN 1;
END';

CALL COMMON.SP_MASTER_INGESTION();