CREATE OR ALTER PROCEDURE ORGANISATION.SP_LOAD_ENTITY_PRODUCT_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ORGANISATION.STAGING_ENTITY_PRODUCT
    FROM @COMMON.ONEVIEW_STAGE/entityProducts/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    UPDATE ORGANISATION.STAGING_ENTITY_PRODUCT as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE ORGANISATION.STAGING_ENTITY_PRODUCT as Target
    SET
        Target.EntityTypeDetailID = src._ID
    FROM COMMON.LOOKUP_DETAIL src
    WHERE src.OneViewID = Target.EntityTypeDetailID
    AND src.ClientID = Target.ClientId;

    RETURN 1;

END';