CREATE OR ALTER PROCEDURE ORGANISATION.SP_LOAD_BUSINESS_UNIT_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ORGANISATION.STAGING_BUSINESS_UNIT
    FROM @COMMON.ONEVIEW_STAGE/businessUnits/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    UPDATE ORGANISATION.STAGING_BUSINESS_UNIT as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    RETURN 1;

END';