CREATE OR ALTER PROCEDURE ORGANISATION.SP_LOAD_OWNER_TYPE_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO ORGANISATION.STAGING_OWNER_TYPE
    FROM @COMMON.ONEVIEW_STAGE/ownerTypes/
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    FORCE = TRUE;

    UPDATE ORGANISATION.STAGING_OWNER_TYPE as Target
    SET 
        Target.ClientID = src._ID
    FROM NEBCOREODMSFDEV.ONEVIEW.DIMCLIENT src
    WHERE target.CLIENTREFERENCE = src.CLIENTREFERENCE;

    UPDATE ORGANISATION.STAGING_OWNER_TYPE as Target
    SET
        Target.DivisionID = src._ID
    FROM Organisation.Division src
    WHERE src.OneViewID = Target.DivisionID
    AND src.ClientID = Target.ClientId;

    RETURN 1;

END';