CREATE OR ALTER PROCEDURE LAN.SP_MASTER_INGESTION()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN
	CALL LAN.SP_LOAD_ACCOUNT_CORPORATE_BILLING_STAGING();
	CALL LAN.SP_LOAD_ACCOUNT_CORPORATE_BILLING();

	RETURN 1;
END';