CREATE OR ALTER PROCEDURE VOICE.SP_LOAD_TMS_DETAIL_PRODUCT_STAGING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    COPY INTO VOICE.STAGING_TMS_DETAIL_PRODUCT
    FROM @COMMON.ONEVIEW_STAGE/tmsDetailProducts
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    FILE_FORMAT = (TYPE = ''PARQUET'')
    ON_ERROR=CONTINUE
    PURGE = TRUE;
    

    RETURN 1;

END';