CREATE OR ALTER PROCEDURE VOICE.SP_MASTER_INGESTION()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN

	CALL VOICE.SP_LOAD_TMS_DETAIL_PRODUCT_STAGING();
	CALL VOICE.SP_LOAD_TMS_DETAIL_PRODUCT();

	RETURN 1;
END';