CREATE OR ALTER PROCEDURE WAN.SP_MASTER_INGESTION()
RETURNS VARCHAR
LANGUAGE SQL
STRICT
EXECUTE AS CALLER
AS '
BEGIN

	CALL WAN.SP_LOAD_ACCOUNT_CORPORATE_BILLING();
	CALL WAN.SP_LOAD_ACCOUNT_CORPORATE_BILLING_STAGING();

	RETURN 1;

END';